Third lab
ShevchenyaIlya/android-report pull request #1
Opened 2020-12-02 18:41 UTC by ShevchenyaIlya

Third laboratory work. Battleship game.

![Выделение_247](https://user-images.githubusercontent.com/50058232/100916566-f99efa00-34e6-11eb-8172-899781ac213d.png)
![Выделение_248](https://user-images.githubusercontent.com/50058232/100916615-07ed1600-34e7-11eb-9340-cdc20894c66f.png)
![Выделение_249](https://user-images.githubusercontent.com/50058232/100916634-0d4a6080-34e7-11eb-8e9b-d81fb400df5f.png)

2020-12-03 13:22 UTC, gmltA requested changes
Good job. But some improvements would make it even better,

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/ProfileActivity.java
> +            StorageReference photoReference = storageReference.child(userConnection.getUser().getImageUrl());
Gravatar avatar source is not implemented. See requirements.

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/ConnectionActivity.java
> +        db.collection("connections")
Network interaction should be extracted from activities (UI layer) into separate independent services.

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/Game.java
> +    private String selectedShip = "Four-decker";
Consider moving vessel types to Enums (or even separate class).

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/Game.java
> +    private String opponentId;
Wouldn't it be better to have some kind of `Player` class with all this data?

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/LoginActivity.java
> +            Toast.makeText(this, "Fill all field.", Toast.LENGTH_SHORT).show();
All this auth-related stuff should be extracted in `AuthService` class.

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/LoginActivity.java
> +        outState.putString("password", password.getText().toString());
What about ViewModels we learned previously?

2020-12-03 13:22 UTC, gmltA commented on Battleship/app/src/main/java/com/example/battleship/MainActivity.java
> +        db.collection("collections")
Such level of nested callbacks gives you a hint that something is not right in the architecture)

2020-12-04 16:33 UTC, gmltA approved these changes
That's better! Good luck during the exam!

2020-12-04 19:28 UTC, ShevchenyaIlya commented
@gmltA Thank you! However I did not correct everything from what you indicated above. Or is it enough to pass this laboratory work?

2020-12-07 14:10 UTC, gmltA commented
> @gmltA Thank you! However I did not correct everything from what you indicated above. Or is it enough to pass this laboratory work?

That's enough.

2020-12-07 16:53 UTC, merged